// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","title":"首页","parentId":"@@/global-layout","id":"1"},"2":{"path":"/docs","title":"文档","parentId":"@@/global-layout","id":"2"},"3":{"path":"/demo/:id","title":"demo","parentId":"@@/global-layout","id":"3"},"4":{"path":"/personal","title":"个人中心","parentId":"@@/global-layout","id":"4"},"5":{"path":"/personal","title":"个人中心","parentId":"4","id":"5"},"6":{"path":"/personal/one","title":"个人中心1","parentId":"4","id":"6"},"7":{"path":"/personal/two","title":"个人中心2","parentId":"4","id":"7"},"8":{"path":"*","title":"404","parentId":"@@/global-layout","id":"8"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__index" */'@/pages/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__docs" */'@/pages/docs.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__demo" */'@/pages/demo.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__personal" */'@/pages/personal.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__personal__personalOne" */'@/pages/personal/personalOne.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__personal__personalOne" */'@/pages/personal/personalOne.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__personal__personalTwo" */'@/pages/personal/personalTwo.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__notfound" */'@/pages/notfound.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/capoo/Documents/web/project_code/react/umi/src/layouts/index.tsx')),
},
  };
}
