import {lazy} from 'react';
const routes = [
  {
    redirect:true,
    from:'/',
    to:'/basicgrammer',
    exact:true,
  },
  {
    path:'/user',
    name:'User',
    component:lazy(()=>import('../../views/UserRouterFive')),
    children:[
      {
        redirect:true,
        from:'/user',
        to:'/user/a',
        exact:true
      },
      {
        path:'/user/a',
        name:'userA',
        component:lazy(()=>import('../../components/Users/router5/UserA'))
      },
      {
        path:'/user/b',
        name:'userB',
        component:lazy(()=>import('../../components/Users/router5/UserB'))
      },
      {
        path:'/user/c',
        name:'userC',
        component:lazy(()=>import('../../components/Users/router5/UserC'))
      }
    ]
  },
  {
    path:'/basicgrammar',
    name:'BasicGrammar',
    component:lazy(()=>import('../../views/ReactBasicGrammar'))
  },
  {
    path:'/compdevbasic',
    name:'CompDevBasic',
    component:lazy(()=>import('../../views/ReactCompDevBasic'))
  },
  {
    path:'/hooks',
    name:'Hooks',
    component:lazy(()=>import('../../views/ReactHooks'))
  },
  {
    path:'/login',
    name:'Login',
    component:lazy(()=>import('../../views/Login'))
  },
  {
    path:'/notfound',
    name:'NotFound',
    component:lazy(()=>import('../../views/NotFound'))
  },
  {
    path:'*',
    component:lazy(()=>import('../../views/ReactBasicGrammar'))
  },
]
export default routes;
